### ISSUE TITLE
github share functionality

### ISSUE THREAD

**Issue by Jmanuel4SandMan** [CN-UPB/upb-son-editor-backend#115]
enable sharing(exporting/importing) a workspace via github

Todos:

# Export
- [x] ask for "repo scope" authorization token(s)
- [x] initialize repository locally
- [x] create repo on github
    - [x] decide for org or user repo
- [x] track remote and local changes
    * remote:  git remote update -> git status -uno
    Remote Changes: "Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded."  
    No Remote Changes: "Your branch is up-to-date with 'origin/master'."
- [x] push repo
- [x] pull repo / update
  - [x] rescan project for changes
- [x] Commit repo (add files)
- [x] Commit repo (remove files)

# Import
- [x] api for receiving github url
- [x] clone repo into workspace
- [x] check if readonly or write access
- [ ] create a fork (maybe)

**Comment by chrz89** [comment]
Fork feature is left out
