### ISSUE TITLE
query service/function by name/vendor/version

### ISSUE THREAD

**Issue by Jmanuel4SandMan** [CN-UPB/upb-son-editor-backend#71]
we need a method to supply the frontend with a service or function by reference of name vendor and version, because this is what is saved to the network descriptors.

Use personal [and if not available external] catalogues?

**Comment by chrz89** [comment]
Task list
[x] Basic api
[x] Looks up service in the current project
[ ] Looks up service in external catalogues
[ ] Looks up service in personal catalogues
